### ISSUE TITLE
CSV importing wrong parsing

### ISSUE THREAD

**Issue by alexsonnay** [vitorfs/colossus#25]
![image](https://user-images.githubusercontent.com/28756458/46033941-ba531280-c0ff-11e8-86d6-82a18196b799.png)

**Comment by vitorfs** [comment]
The idea here is that you instruct Colossus on how to import your data properly, from a csv file in any format.

On the select input on the header of the table you can define the mapping and tell Colossus what to do with this field. For now we have limited fields. Custom fields are on the roadmap.

**Comment by alexsonnay** [comment]
Okay. The issue was that I only had email addresses and not names associated with them. There is no way to paste together the "broken" email lists (example : iloveyou@gmail.com becomes iloveyou as the email address and @gmail.com becomes the name). The only workaround is to force a second column in the CSV file and write names.

**Comment by vitorfs** [comment]
Ah that's interesting. Thanks for reporting that!

It is indeed a bug. The way I'm using Python's csv utility, I try to guess what is the column separator (comma, semicolon, tabs, etc). 

Because you only had emails in the csv file, the parser thought the "@" was the separator, so it ended up splitting the name and domain into two columns, instead of keeping only one column.

I'll release a fix soon
