### ISSUE TITLE
Gmail SMTP not working

### ISSUE THREAD

**Issue by alexsonnay** [vitorfs/colossus#29]
I tried using Gmail SMTP but nothing happens. Any idea ?
```
EMAIL_SUBJECT_PREFIX` = '[Colossus] '

SERVER_EMAIL = config('SERVER_EMAIL', default='colossus@simpleisbetterthancomplex.com')

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='hello@mysite.com')

EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')

EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')

EMAIL_PORT = config('EMAIL_PORT', default=465, cast=int)

EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='myemail@gmail.com')

EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='myPassword')

EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
```

**Comment by vitorfs** [comment]
Make sure you have SMTP backend configurated:

```python
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
```

Also keep in mind that Gmail is not intended to send transactional emails via SMTP, so it is not suitable for production usage (you will also have limit of emails you can send per day, because it is a personal email)

You may need to tweak some settings on your Gmail account: https://support.google.com/accounts/answer/6010255

There are better options like Mailgun and SendGrid that are designed for this use case. Both offer a handful of free messages per month. 

Some tutorials that can help you to get started:

* [How to Configure Mailgun To Send Emails in a Django Project](https://simpleisbetterthancomplex.com/tutorial/2017/05/27/how-to-configure-mailgun-to-send-emails-in-a-django-app.html)
* [How to Send Email in a Django App Using SendGrid](https://simpleisbetterthancomplex.com/tutorial/2016/06/13/how-to-send-email.html)

**Comment by alexsonnay** [comment]
Thanks. I use Gsuite, however even setting email backend with smtp.gmail.com it doesn't work...

**Comment by alexsonnay** [comment]
I tried with MailGun, and nothing happens...

```
EMAIL_SUBJECT_PREFIX = '[Colossus] '

SERVER_EMAIL = config('SERVER_EMAIL', default='root@localhost')

DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='webmaster@localhost')

EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.smtp.EmailBackend')

EMAIL_HOST = config('EMAIL_HOST', default='smtp.mailgun.org')

EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)

EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='postmaster@mg.mysite.com')

EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='mailgunPassword')

EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
```

Any idea ?
